SELECT TITLE, NAME, SURNAME
FROM BOOKAUTHORS 
LEFT JOIN AUTHOR ON BOOKAUTHORS.AUTHORID = AUTHOR.AUTHORID
LEFT JOIN BOOK ON BOOKAUTHORS.BOOKID = BOOK.BOOKID
WHERE NAME LIKE 'YEHOR' AND SURNAME LIKE 'DATSENKO';